version: '3'

services:
  nginx:
    ports:
      - '3000:80'

  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=mugil
      - MONGO_PASSWORD=mypassword
      - SESSION_SECRET=sesionisasecret
    command: npm run dev
